### PR TITLE
updates to the Gemfile and wrapper to use the Splunk Ruby Distro

### PR DESCRIPTION
**Pull request by tsloughter-splunk**

### CODE REVIEW

**Review by breedx-splk — COMMENTED** [review]
Are we going to need some specifics from our distro? Else, can it wait until we actually use it?

**Comment by tsloughter-splunk** [comment]
@breedx-splk we will remove code from the wrapper as it duplicates some stuff. The reason I'm doing this in small chunks is partly just that these are my first changes to the project and want to keep possible things I broke small in each PR testing :)

**Comment by tsloughter-splunk** [comment]
So CI passes when manually triggered, but this gitlab check in github options doesn't update. I've tried kicking it with new commits, but nothing.

@breedx-splk any idea on how t unstick it or should I try opening a new PR (again)

**Comment by breedx-splk** [comment]
> So CI passes when manually triggered, but this gitlab check in github options doesn't update. I've tried kicking it with new commits, but nothing.
> 
> @breedx-splk any idea on how t unstick it or should I try opening a new PR (again)

Yeah I dunno. I think I've seen that elsewhere too. Meh. Probably open a new one 🤷🏻

**Comment by tsloughter-splunk** [comment]
Replaced by #100

**Pull request closed without merging**
